services:
    sonata.admin.cms_menu:
        class: Cine\CmsBundle\Admin\MenuAdmin
        tags:
             - { name: sonata.admin, manager_type: orm, group: "Content", label: "Menu" }
        arguments:
             - ~
             - Cine\CmsBundle\Entity\Menu
             - ~

    sonata.admin.cms_menu_item:
        class: Cine\CmsBundle\Admin\MenuItemAdmin
        tags:
             - { name: sonata.admin, manager_type: orm, group: "Content", label: "Elements menu" }
        arguments:
             - ~
             - Cine\CmsBundle\Entity\MenuItem
             - ~
        calls:
            - [ setEntityManager, [ @doctrine.orm.entity_manager ]]

    sonata.admin.cms_article_etat:
        class: Cine\CmsBundle\Admin\ArticleEtatAdmin
        tags:
             - { name: sonata.admin, manager_type: orm, group: "Content", label: "Etat article" }
        arguments:
             - ~
             - Cine\CmsBundle\Entity\ArticleEtat
             - ~

    sonata.admin.cms_article:
        class: Cine\CmsBundle\Admin\ArticleAdmin
        tags:
             - { name: sonata.admin, manager_type: orm, group: "Content", label: "Article" }
        arguments:
             - ~
             - Cine\CmsBundle\Entity\Article
             - ~
        calls:
            - [ setSecurityContext, [ @security.context ]]