services:
    cine_user.registration.form.type:
        class: Cine\UserBundle\Form\Type\RegistrationFormType
        arguments: [Cine\UserBundle\Entity\User]
        tags:
            - { name: form.type, alias: cine_user_registration }

    cine_user.registration.listener:
        class: Cine\UserBundle\Service\RegisterListener
        arguments:
            - @cine_user.manager.groupe
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.completed, method: registerCompleted }

    cine_user.manager.groupe:
        class: Cine\UserBundle\Service\GroupeManager
        arguments:
             - @doctrine.orm.entity_manager
