# Sonata Configuration
sonata_admin:
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig

    dashboard:
        groups:
            cine.admin.group.content:
                label: Utilisateurs
                items:
                    - sonata.admin.usr_user
                    - sonata.admin.user_group
                    - sonata.admin.usr_famille