# Sonata Configuration
sonata_admin:
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
        layout:  SonataAdminBundle::layout.html.twig

    dashboard:
        groups:
            cine.admin.group.content:
                label: Utilisateurs
                items:
                    - sonata.admin.usr_user
                    - sonata.admin.user_group
                    - sonata.admin.usr_famille
            cine.admin.group.cms:
                label: Cms
                items:
                    - sonata.admin.cms_article
                    - sonata.admin.cms_article_etat
                    - sonata.admin.cms_menu
            cine.admin.group.fiche:
                label: Cinema
                items:
                    - sonata.admin.cin_film
                    - sonata.admin.cin_serie
                    - sonata.admin.cin_cm
                    - sonata.admin.cin_fest
            cine.admin.group.media:
                label: Médias
                items:
                    - cine.admin.media
                    - sonata.media.admin.gallery