services:
    sonata.admin.usr_user:
        class: Cine\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Utilisateur" }
        arguments:
            - ~
            - Cine\UserBundle\Entity\User
            - ~

    sonata.admin.user_group:
        class: Cine\UserBundle\Admin\GroupeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Groupe de Roles" }
        arguments:
            - ~
            - Cine\UserBundle\Entity\Groupe
            - ~
        calls:
             - [ setAllSecurityRoles, [%allAdminSecurityRoles%] ]