<?php

namespace Cine\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function getMenu($id) {
        $qb = $this->createQueryBuilder('m')
                ->where('m.id = :menuId')
                    ->setParameter(':menuId', $id);
        return $qb->getQuery()->getOneOrNullResult();
    }

}